// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheDonut.Infrastructure.Context;

namespace TheDonut.Infrastructure.Migrations
{
    [DbContext(typeof(DonutDbContext))]
    [Migration("20211221014557_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TheDonut.Domain.Entities.Donut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Donut");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chocolate Belga",
                            Price = 8.5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chocolate Branco",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frutas Vermelhas",
                            Price = 6.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
